spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://football-db:5432/football-db
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
